import re
import json

text = """Pregunta 1Si una matriz cuadrada $A$ de orden 3 tiene un determinante igual a 5 ($|A| = 5$), ¿cuál es el determinante de su transpuesta $|A^T|$?
A) -5B) 5C) 15D) 1/5Respuesta correcta: BJustificación: Por propiedades de los determinantes, el determinante de la matriz transpuesta es exactamente igual al determinante de la matriz original ($|A^T| = |A|$).Pregunta 2Si multiplicamos todos los elementos de una matriz cuadrada $A$ de orden $n=3$ por una constante $\\alpha = 2$, sabiendo que $|A| = 10$, el determinante de la nueva matriz $|2 \cdot A|$ será:
A) 20B) 30C) 80D) 60Respuesta correcta: CJustificación: Si se multiplica a todos los elementos de una matriz de orden $n$ por una constante $\\alpha$, el determinante queda multiplicado por $\\alpha^n$. En este caso, $2^3 \cdot 10 = 8 \cdot 10 = 80$.Pregunta 3¿Qué le ocurre al determinante de una matriz si se intercambian entre sí dos de sus filas paralelas?
A) No se modifica.B) Se multiplica por cero.C) Cambia de signo.D) Se eleva al cuadrado.Respuesta correcta: CJustificación: Por propiedad, si en una matriz se cambian dos líneas paralelas entre sí (filas o columnas), el determinante cambia de signo.Pregunta 4Si en un examen te presentan una matriz rectangular de orden $3 \\times 4$, ¿cuál es su determinante?
A) Es igual a 0.B) No se puede calcular porque el determinante está asociado únicamente a matrices cuadradas.C) Es igual al rango de la matriz.D) Depende de los términos independientes.Respuesta correcta: BJustificación: La definición formal establece que el determinante es un número real asociado única y exclusivamente a una matriz cuadrada.Pregunta 5Dada una matriz triangular superior $A$ de orden 3 cuyos elementos en la diagonal principal son $a_{11}=2$, $a_{22}=-3$ y $a_{33}=4$, su determinante es:
A) 3B) 0C) -24D) 24Respuesta correcta: CJustificación: El determinante de una matriz diagonal o de una matriz triangular es igual al producto de los elementos de la diagonal principal. En este caso, $2 \cdot (-3) \cdot 4 = -24$.Pregunta 6Si a la fila 2 de una matriz cuadrada $A$ le sumamos la fila 1 previamente multiplicada por una constante $\\alpha = 5$, ¿qué le ocurre al valor del determinante de la nueva matriz resultante?
A) Queda multiplicado por 5.B) No se modifica.C) Cambia de signo.D) Se vuelve cero.Respuesta correcta: BJustificación: Si a los elementos de una línea cualquiera les sumamos los elementos de otra línea paralela multiplicada por una constante, el determinante no se modifica.Pregunta 7El determinante de una matriz cuadrada es cero si y solo si sus líneas paralelas constituyen un conjunto de vectores:
A) Linealmente Independientes (L.I.).B) Linealmente Dependientes (L.D.).C) Ortogonales.D) Nulos.Respuesta correcta: BJustificación: La propiedad indica que el determinante es cero si y solo si sus líneas paralelas constituyen un conjunto de vectores linealmente dependientes (L.D.).Pregunta 8¿Cuál de las siguientes situaciones garantiza que el determinante de una matriz cuadrada sea igual a cero de forma inmediata?
A) Que tenga todos los elementos de la diagonal principal iguales a 1.B) Que tenga una línea completa nula (de ceros).C) Que sea una matriz invertible.D) Que sea una matriz transpuesta.Respuesta correcta: BJustificación: El determinante será cero si la matriz tiene una línea nula, si tiene dos líneas proporcionales o si una línea es combinación lineal de otras.Pregunta 9Dadas dos matrices cuadradas del mismo orden $B$ y $C$, donde $|B| = 4$ y $|C| = -2$, el determinante del producto $|B \cdot C|$ es:
A) 2B) -8C) -2D) 8Respuesta correcta: BJustificación: El determinante de un producto de matrices cuadradas es igual al producto de los determinantes de dichas matrices ($|B \cdot C| = |B| \cdot |C|$). Por ende, $4 \cdot (-2) = -8$.Pregunta 10Si multiplicamos una sola fila de una matriz $A$ por una constante $\\alpha = -3$, sabiendo que el determinante original era $|A| = 5$, el nuevo determinante será:
A) -15B) -45C) 5D) -5Respuesta correcta: AJustificación: Si se multiplica a todos los elementos de una sola línea (fila o columna) de una matriz por una constante, el determinante queda multiplicado por dicha constante. Entonces, $-3 \cdot 5 = -15$.Bloque 2: Regla de Cramer (Sistemas Cuadrados)Pregunta 11La Regla de Cramer es un método matricial utilizable para resolver sistemas de ecuaciones lineales que cumplen con la siguiente condición estructural básica:
A) Deben tener más ecuaciones que incógnitas.B) Deben ser sistemas donde el número de ecuaciones es igual al número de incógnitas (sistemas cuadrados).C) Deben ser sistemas homogéneos obligatoriamente.D) Deben poseer una matriz de coeficientes rectangular.Respuesta correcta: BJustificación: Para aplicar este método, el número de ecuaciones debe ser igual al número de incógnitas, conformando un sistema cuadrado.Pregunta 12Para poder asegurar que un sistema cuadrado tiene una solución única mediante la Regla de Cramer, el determinante de la matriz de coeficientes ($\\Delta$) debe ser:
A) Igual a cero.B) Menor a cero.C) Distinto de cero ($\\Delta \\neq 0$).D) Mayor a uno.Respuesta correcta: CJustificación: El sistema tendrá solución única (compatible determinado) si y solo si el determinante asociado a la matriz de coeficientes es distinto de cero.Pregunta 13En la Regla de Cramer, ¿cómo se construye el determinante modificado $\\Delta_y$ correspondiente a la variable $y$?
A) Multiplicando la matriz de coeficientes por el vector de términos independientes.B) Reemplazando la columna de los coeficientes de la variable $y$ por el vector de términos independientes.C) Reemplazando la fila 1 de la matriz por ceros.D) Calculando la transpuesta de la matriz de coeficientes.Respuesta correcta: BJustificación: El determinante $\\Delta_y$ se obtiene de reemplazar específicamente la columna de los coeficientes de la variable $y$ por los términos independientes del sistema.Pregunta 14Si al intentar aplicar la Regla de Cramer en un sistema de $3 \\times 3$ obtenemos que $\\Delta = 0$, y además los determinantes modificados son $\\Delta_x = 0$, $\\Delta_y = 0$ y $\\Delta_z = 0$, podemos concluir que:
A) El sistema tiene una solución única.B) El sistema no tiene solución (es incompatible).C) El sistema tiene un número infinito de soluciones.D) Se copió mal un número en la matriz.Respuesta correcta: CJustificación: Si el determinante principal es cero y todos los determinantes modificados también son cero, el sistema tiene un número infinito de soluciones (SCI).Pregunta 15Si en un sistema de ecuaciones cuadrados encontrás que $\\Delta = 0$ pero al menos uno de los determinantes modificados (por ejemplo, $\\Delta_x$) es distinto de cero ($\\Delta_x \\neq 0$), el sistema se clasifica como:
A) Compatible Determinado.B) Incompatible (no tiene solución).C) Compatible Indeterminado.D) Homogéneo Trivial.Respuesta correcta: BJustificación: Si $\\Delta = 0$, el sistema no tiene solución única. Al haber un determinante modificado distinto de cero, la división matemática daría un número dividido cero (indefinido), lo que caracteriza a un sistema Incompatible (SI).Bloque 3: Operaciones Elementales y Matrices ElementalesPregunta 16¿Cuáles de los siguientes cambios representa una operación elemental por fila válida sobre una matriz?
A) Sumar una constante no nula a cada elemento de una fila.B) Multiplicar una fila por una constante igual a cero.C) Intercambiar la posición de dos filas paralelas.D) Multiplicar una fila por otra fila paralela.Respuesta correcta: CJustificación: Las operaciones elementales por fila permitidas son tres: intercambio de dos filas, multiplicación de una fila por una constante no nula, y adición a una fila de otra paralela multiplicada por un escalar.Pregunta 17Si te dicen que la operación elemental realizada es $f_2 : f_2 + (-2) \cdot f_1$, ¿cuál es la fila que resulta modificada en la matriz resultante?
A) La fila 1.B) La fila 2.C) Ambas filas cambian sus valores.D) Ninguna, el determinante se mantiene igual.Respuesta correcta: BJustificación: En la notación de operaciones elementales de adición, la fila que se modifica es la que recibe la suma (en este caso la fila 2), mientras que la fila utilizada como pivote (fila 1) permanece intacta.Pregunta 18¿Qué es una matriz elemental?
A) Cualquier matriz que tiene ceros y unos en sus elementos.B) Una matriz cuadrada que surge de aplicar una única operación elemental por fila a la matriz identidad.C) La matriz inversa de una matriz rectangular.D) Una matriz que tiene determinante igual a cero.Respuesta correcta: BJustificación: Se denominan matrices elementales a aquellas que se obtienen a partir de la matriz identidad realizando solo una de las operaciones elementales por fila.Pregunta 19Dada la siguiente matriz $E = \\begin{pmatrix} 1 & 0 \\\\ 0 & -3 \\end{pmatrix}$, ¿podemos afirmar que es una matriz elemental?
A) No, porque tiene un número negativo.B) Sí, porque surge de aplicar la operación elemental de multiplicar la fila 2 de la identidad por la constante -3.C) No, porque no es equivalente a la identidad.D) Sí, porque su determinante es cero.Respuesta correcta: BJustificación: La matriz identidad de $2 \\times 2$ es $\\begin{pmatrix} 1 & 0 \\\\ 0 & 1 \\end{pmatrix}$. Si multiplicamos su fila 2 por -3 (operación elemental válida), obtenemos exactamente la matriz $E$, por lo que califica como matriz elemental.Pregunta 20Dada la matriz $H = \\begin{pmatrix} 0 & 1 \\\\ -3 & 0 \\end{pmatrix}$, ¿por qué el texto afirma que NO es una matriz elemental, aunque sea equivalente a la identidad?
A) Porque su determinante es nulo.B) Porque no es una matriz cuadrada.C) Porque para llegar a ella desde la identidad se requiere efectuar más de una operación elemental por fila.D) Porque no tiene un pivote igual a 1 en la primera fila.Respuesta correcta: CJustificación: Una matriz elemental debe surgir de efectuar una única operación elemental sobre la identidad. Para transformar la identidad en $H$, se debió hacer un intercambio de filas y además una multiplicación por un escalar, por ende, es equivalente pero no elemental.Bloque 4: Matriz Inversa y Método de la InversaPregunta 21Se dice que una matriz cuadrada $A$ es \"regular\" si cumple con la condición de tener:
A) Un determinante igual a cero.B) Un determinante distinto de cero, lo que implica que admite matriz inversa.C) Únicamente números reales positivos en su interior.D) El mismo número de filas que de columnas únicamente.Respuesta correcta: BJustificación: Una matriz es regular si su determinante es distinto de cero, lo cual es la condición necesaria y suficiente para que sea inversible (admita inversa).Pregunta 22Si una matriz cuadrada $A$ tiene un determinante igual a cero ($|A| = 0$), se la denomina:
A) Regular.B) Triangular.C) Singular.D) Elemental.Respuesta correcta: CJustificación: Por definición, se dice que una matriz $A$ es singular si su determinante es igual a cero. Las matrices singulares no tienen inversa.Pregunta 23¿Cuál es la propiedad fundamental que define la relación entre una matriz cuadrada $A$ y su matriz inversa $A^{-1}$?
A) $A + A^{-1} = I$B) $A \cdot A^{-1} = A^{-1} \cdot A = I$C) $A \cdot A^{-1} = \\emptyset$D) $(A^{-1})^{-1} = I$Respuesta correcta: BJustificación: Por definición de matriz inversa, el producto de una matriz por su inversa en cualquier orden debe dar como resultado la matriz identidad ($I$).Pregunta 24Por propiedad de la inversa de un producto de matrices inversibles, la expresión $(A \cdot B)^{-1}$ es igual a:
A) $A^{-1} \cdot B^{-1}$B) $B^{-1} \cdot A^{-1}$C) $(B \cdot A)^T$D) $A \cdot B \cdot I$Respuesta correcta: BJustificación: La inversa de un producto de matrices inversibles es igual al producto de las inversas en el orden invertido: $(A \cdot B)^{-1} = B^{-1} \cdot A^{-1}$.Pregunta 25Si el determinante de una matriz regular es $|A| = 4$, el determinante de su matriz inversa $|A^{-1}|$ será:
A) -4B) 1/4C) 16D) 2Respuesta correcta: BJustificación: Por propiedad, el determinante de la matriz inversa es igual al recíproco del determinante de la matriz original: $|A^{-1}| = \\frac{1}{|A|}$. En este caso, $1/4$.Pregunta 26Dada una matriz diagonal regular cuyos elementos en la diagonal principal son $d_{11}=3$ y $d_{22}=-4$, su matriz inversa tendrá en la diagonal principal los valores:
A) -3 y 4B) 3 y -4C) 1/3 y -1/4D) 9 y 16Respuesta correcta: CJustificación: La inversa de una matriz diagonal regular es otra matriz diagonal que tiene en su diagonal principal a los recíprocos de los elementos originales. Por lo tanto, quedan $1/3$ y $-1/4$.Pregunta 27El método de Jordan para obtener la inversa de una matriz se basa en armar una matriz ampliada con la estructura:
A) $(A | B)$, donde $B$ es el vector de términos independientes.B) $(A | I)$, donde $I$ es la matriz identidad del mismo orden.C) $(A | A^T)$, donde $A^T$ es la transpuesta.D) $(I | B)$, donde $I$ es la identidad.Respuesta correcta: BJustificación: El procedimiento parte de la matriz $A$ ampliada con la matriz identidad del mismo orden $(A | I)$, y se le aplican operaciones elementales hasta lograr que la izquierda se convierta en la identidad, quedando la inversa a la derecha.Pregunta 28Si estás resolviendo un sistema compatible determinado expresado como $A \cdot X = B$ usando el método de la inversa, la solución para el vector de incógnitas $X$ se calcula como:
A) $X = B \cdot A^{-1}$B) $X = A^{-1} \cdot B$C) $X = A \cdot B$D) $X = \\frac{B}{A}$Respuesta correcta: BJustificación: Multiplicando por la izquierda por $A^{-1}$ en ambos miembros de la ecuación matricial, se llega a que la solución única está dada por $X = A^{-1} \cdot B$.Pregunta 29Si en un sistema de ecuaciones de orden 3 se verifica que la fila 3 es una combinación lineal de las filas 1 y 2 ($f_3 = 2 \cdot f_1 + f_2$), ¿se puede aplicar el método de la inversa para resolverlo?
A) Sí, porque el sistema tiene 3 ecuaciones.B) No, porque al ser una fila combinación lineal de las otras, el determinante de $A$ es cero, no admite inversa y el método falla.C) Sí, porque las operaciones elementales acomodan la fila.D) Depende de los valores de los términos independientes.Respuesta correcta: BJustificación: Si una fila es combinación lineal de otras paralelas, el conjunto es linealmente dependiente (L.D.), lo que hace que el determinante de la matriz sea cero (matriz singular), impidiendo la existencia de $A^{-1}$.Pregunta 30¿Cuál de las siguientes expresiones teóricas es FALSA respecto a las propiedades de las matrices inversas?
A) $((A)^{-1})^{-1} = A$B) $(k \cdot A)^{-1} = \\frac{1}{k} \cdot A^{-1}$ (con $k \\neq 0$)C) $(A \cdot B)^{-1} = A^{-1} \cdot B^{-1}$D) $A \cdot A^{-1} = I$Respuesta correcta: CJustificación: Como se vio en la propiedad, $(A \cdot B)^{-1}$ debe dar el producto con el orden invertido ($B^{-1} \cdot A^{-1}$). La opción C muestra el orden directo, lo cual es matemáticamente incorrecto en matrices ya que el producto no es conmutativo general.Bloque 5: Rango de una MatrizPregunta 31El rango de una matriz $A$ de orden $m \\times n$ se define formalmente como:
A) El número total de elementos no nulos de la matriz.B) El número máximo de líneas paralelas (filas o columnas) linealmente independientes que posee la matriz.C) La multiplicación del número de filas por el número de columnas.D) El valor de su determinante principal.Respuesta correcta: BJustificación: El rango de una matriz está dado de forma estricta por el número máximo de líneas paralelas linealmente independientes que posee.Pregunta 32Si una matriz escalonada y reducida por filas tiene dos filas con valores numéricos y una tercera fila compuesta completamente por ceros (fila nula), su rango es:
A) 3B) 1C) 2D) 0Respuesta correcta: CJustificación: Al llevar una matriz a su forma escalonada, el rango es exactamente igual a la cantidad de filas no nulas de dicha matriz. Como hay dos filas no nulas, el rango es 2.Pregunta 33Si tenemos una matriz rectangular de orden $4 \\times 3$, ¿cuál es el rango máximo teórico que podría llegar a tener?
A) 4B) 3C) 7D) 1Respuesta correcta: BJustificación: Por propiedad, el rango de una matriz no puede exceder al mínimo entre el número de filas y el número de columnas que posee ($r(A) \\le \\min(m, n)$). El mínimo entre 4 y 3 es 3.Pregunta 34¿Qué le sucede al rango de una matriz si realizamos operaciones elementales por fila sobre ella?
A) El rango aumenta según el valor del escalar utilizado.B) El rango disminuye si se intercambian las filas.C) Las matrices equivalentes por filas tienen el mismo rango (no cambia).D) El rango se vuelve cero automáticamente.Respuesta correcta: CJustificación: Un teorema fundamental establece que al realizar operaciones elementales por fila la matriz cambia de forma pero conserva de manera intacta su rango.Pregunta 35¿Cuál es el rango de la matriz identidad de orden 3 ($I_3$)?
A) 1B) 0C) 3D) Indeterminado.Respuesta correcta: CJustificación: Por propiedad, el rango de la matriz identidad es siempre igual al orden de la misma: $r(I_n) = n$. Para $I_3$, el rango es 3.Pregunta 36Si calculamos el rango de una matriz $A$ y luego el rango de su transpuesta $A^T$, podemos asegurar que:
A) $r(A) > r(A^T)$B) $r(A) = r(A^T)$C) $r(A) < r(A^T)$D) El rango de la transpuesta siempre es igual al orden de la matriz.Respuesta correcta: BJustificación: El rango de una matriz es igual al rango de su transpuesta ($r(A) = r(A^T)$), ya que el rango fila es matemáticamente igual al rango columna.Pregunta 37Si el determinante de una matriz cuadrada de orden $n=3$ es igual a cero ($|A| = 0$), ¿qué podemos afirmar sobre su rango?
A) Que su rango es máximo e igual a 3.B) Que su rango es estrictamente menor a 3 ($r(A) < 3$).C) Que su rango es igual a 0.D) Que no se puede calcular el rango.Respuesta correcta: BJustificación: Si una matriz es singular ($|A| = 0$), el conjunto de vectores filas es linealmente dependiente, lo que implica que su rango es menor que el orden de la matriz ($r(A) < n$).Bloque 6: Sistemas de Ecuaciones y Notación MatricialPregunta 38¿Qué es la \"matriz ampliada\" de un sistema de ecuaciones lineales?
A) La matriz que resulta de multiplicar la matriz de coeficientes por la transpuesta.B) La matriz que surge de agregar la columna del vector de términos independientes a la derecha de la matriz de coeficientes.C) Una matriz que tiene el doble de filas que la matriz original.D) La matriz identidad que se usa en el método de la inversa.Respuesta correcta: BJustificación: La matriz ampliada del sistema (denotada $A|B$) surge de agregar el vector de términos independientes a la matriz de coeficientes.Pregunta 39Dos sistemas de ecuaciones lineales se clasifican formalmente como \"equivalentes\" si cumplen con la condición de tener:
A) El mismo número de ecuaciones y de incógnitas.B) Los mismos coeficientes numéricos exactos.C) El mismo conjunto solución.D) Matrices de coeficientes simétricas.Respuesta correcta: CJustificación: Dos o más sistemas se dicen equivalentes si y solo si comparten exactamente el mismo conjunto solución.Pregunta 40Si un sistema de ecuaciones tiene la estructura $A \cdot X = B$ y el vector de términos independientes $B$ está compuesto completamente por ceros ($B = \\emptyset$), el sistema se denomina:
A) No homogéneo.B) Cuadrado regular.C) Homogéneo.D) Incompatible.Respuesta correcta: CJustificación: Un sistema es homogéneo si sus términos independientes son todos iguales a cero.Bloque 7: Teorema de Rouché-Frobenius y CorolarioPregunta 41El enunciado del Teorema de Rouché-Frobenius establece textualmente que un sistema de ecuaciones lineales será compatible (tiene solución) si y solo si:
A) El determinante de la matriz de coeficientes es mayor a cero.B) El rango de la matriz de coeficientes es igual al rango de la matriz ampliada ($r(A) = r(A|B)$).C) El sistema es cuadrado y regular.D) Tiene el mismo número de ecuaciones que de incógnitas.Respuesta correcta: BJustificación: El teorema indica que el sistema es compatible si y solo si el rango de la matriz de coeficientes coincide con el rango de la matriz ampliada correspondiente.Pregunta 42Según el corolario del Teorema de Rouché-Frobenius, ¿cuándo un sistema es Compatible Determinado (solución única)?
A) Cuando $r(A) = r(A|B) < n$ (siendo $n$ el número de incógnitas).B) Cuando $r(A) < r(A|B)$.C) Cuando el rango de la matriz del sistema y de la ampliada es igual al número de incógnitas ($r(A) = r(A|B) = n$).D) Cuando el sistema es homogéneo únicamente.Respuesta correcta: CJustificación: El sistema tiene solución única (compatible determinado) si y solo si ambos rangos son iguales y además coinciden con el número total de incógnitas del problema.Pregunta 43Si al reducir la matriz ampliada de un sistema obtenés que $r(A) = 2$ y $r(A|B) = 3$, ¿cómo se clasifica el sistema según el teorema?
A) Compatible Determinado.B) Compatible Indeterminado.C) Incompatible (no tiene solución).D) Homogéneo.Respuesta correcta: CJustificación: Si el rango de la matriz de coeficientes es menor que el rango de la matriz ampliada ($r(A) < r(A|B)$), el sistema se clasifica como incompatible, es decir, carece de solución.Pregunta 44Si un sistema de 3 incógnitas tiene rangos $r(A) = r(A|B) = 2$, el sistema es:
A) Compatible Determinado.B) Compatible Indeterminado (tiene infinitas soluciones).C) Incompatible.D) Singular elemental.Respuesta correcta: BJustificación: Al ser los rangos iguales, el sistema tiene solución (compatible), pero como el valor numérico del rango (2) es menor que el número de incógnitas ($n=3$), el sistema cuenta con infinitas soluciones (indeterminado).Pregunta 45¿Por qué es imposible que en un análisis de sistemas se dé el caso de que $r(A) > r(A|B)$?
A) Porque la matriz de coeficientes siempre tiene más columnas.B) Porque la matriz ampliada contiene a toda la matriz de coeficientes más una columna extra, por lo que su rango nunca puede ser menor.C) Porque el teorema de Rouché-Frobenius lo prohíbe explícitamente.D) Porque los términos independientes nunca valen cero.Respuesta correcta: BJustificación: Al agregar una columna a una matriz, el número de vectores linealmente independientes puede mantenerse igual o aumentar, pero jamás disminuir. Por lo tanto, el rango de la ampliada siempre es mayor o igual al rango de $A$.Pregunta 46Un sistema lineal de tipo Homogéneo ($A \cdot X = \\emptyset$) tiene la particularidad de que:
A) Siempre es incompatible.B) Nunca puede ser incompatible, ya que los rangos de $A$ y de la ampliada siempre van a ser exactamente iguales.C) Solo admite soluciones negativas.D) No se puede resolver por el método de Gauss-Jordan.Respuesta correcta: BJustificación: En un sistema homogéneo, agregar una columna llena de ceros a la matriz de coeficientes no añade ningún vector linealmente independiente. Por ende, $r(A)$ siempre es igual a $r(A|B)$, garantizando que el sistema sea siempre compatible (admita al menos la solución trivial).Bloque 8: Método de Gauss-Jordan y Casos PrácticosPregunta 47El método de resolución de sistemas de Gauss-Jordan consiste mecánicamente en operar sobre la matriz ampliada hasta conseguir que la sección de los coeficientes se transformé en:
A) Una matriz nula.B) Una matriz escalonada reducida por filas.C) Una matriz triangular superior únicamente.D) La matriz transpuesta de los términos independientes.Respuesta correcta: BJustificación: El método consiste en aplicar operaciones elementales por fila sobre la matriz ampliada buscando llevar la sección de la matriz de coeficientes $A$ a su forma escalonada reducida por filas.Pregunta 48¿Cuál es la principal ventaja operativa del método de Gauss-Jordan sobre el método de la inversa o la regla de Cramer?
A) Que es más corto y no usa sumas.B) Que se puede aplicar absolutamente SIEMPRE, sin importar si el sistema es cuadrado, rectangular, compatible o incompatible.C) Que no requiere el uso de operaciones elementales.D) Que solo sirve para sistemas que tienen solución única.Respuesta correcta: BJustificación: A diferencia de Cramer o la Inversa (que exigen matrices cuadradas y regulares), el método de Gauss-Jordan es universal y se puede aplicar siempre, brindando la caracterización inmediata del sistema.Pregunta 49Si al finalizar el escalonamiento por Gauss-Jordan de un sistema con variables $x, y, z$, la última fila de la matriz ampliada reducida queda con los valores: $0 \quad 0 \quad 0 \quad | \quad -1.5$, la interpretación correcta es:
A) Que la variable $z$ es igual a -1.5.B) Que el sistema es compatible indeterminado y $z$ es una variable libre.C) Que el sistema es incompatible (sin solución) porque se llega al absurdo matemático de que $0 = -1.5$.D) Que hay que volver a realizar los cálculos porque se cometió un error de signos.Respuesta correcta: CJustificación: Esa fila equivale a escribir la ecuación $0x + 0y + 0z = -1.5$, lo cual es un absurdo matemático. Esto demuestra de forma práctica que $r(A) < r(A|B)$, por lo que el sistema no tiene solución.Pregunta 50Caso práctico: Si en el problema de la fábrica de pastas (de tus apuntes), se decide eliminar el proceso de secado porque la producción se venderá en su totalidad como pasta fresca, ¿qué cambio estructural experimenta el sistema de ecuaciones original?
A) Se duplica el número de incógnitas.B) El sistema pierde una ecuación, pasando de tener 4 ecuaciones a tener 3 ecuaciones.C) Se transforma inmediatamente en un sistema incompatible.D) La matriz de coeficientes pasa a ser una matriz diagonal.Respuesta correcta: BJustificación: Como cada ecuación representa las restricciones de tiempo asociadas a una máquina en particular (amasadora, extrusora, secadora), si se elimina la sección de secado, el sistema pierde la condición matemática de esa máquina, quedándose con una ecuación menos."""

questions = []
text = re.sub(r'Bloque \d+: .*?(?=Pregunta)', '', text)

pattern = r'Pregunta \d+(.*?)(?=A\))A\) (.*?)(?=B\))B\) (.*?)(?=C\))C\) (.*?)(?=D\)|Respuesta correcta:)(?:D\) (.*?))?Respuesta correcta: ([A-D])Justificación: (.*?)(?=Pregunta \d+|$)'
matches = re.findall(pattern, text, re.DOTALL)

for i, m in enumerate(matches):
    q_text, a, b, c, d, correct, just = [s.strip() if s else s for s in m]
    options = [
        {'id': 'A', 'text': a},
        {'id': 'B', 'text': b},
        {'id': 'C', 'text': c}
    ]
    if d:
        options.append({'id': 'D', 'text': d})
    
    questions.append({
        'id': i + 1,
        'text': q_text,
        'options': options,
        'correctId': correct,
        'justification': just
    })

with open('algebra_questions.json', 'w', encoding='utf-8') as f:
    json.dump(questions, f, ensure_ascii=False, indent=4)

with open('algebra_questions.js', 'w', encoding='utf-8') as f:
    f.write('export const algebraQuestions = ')
    json.dump(questions, f, ensure_ascii=False, indent=4)
    f.write(';')
